version: '3.9'
services:
  backend:
    profiles:
      - prod
    container_name: attendance_backend
    build:
      context: .
    environment:
      - TZ=Asia/Shanghai
      # 指定redis 密码和mysql 密码，请和下面的service配置保持一致
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
      # 花里胡哨
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    ports:
      - 8080:8080
  backend_dev:
    # 开发环境容器，只要容器提供gradle环境即可
    container_name: attendance_backend_dev
    image: gradle:6-jdk11-alpine
    command: gradle bootRun --info
    working_dir: /home/gradle/attendance/
    volumes:
      # 直接映射本地文件夹，避免复制
      - .:/home/gradle/attendance
      - m2:/home/gradle/.m2/repository
      - gradle:/home/gradle/.gradle
    environment:
      - TZ=Asia/Shanghai
      # 指定redis 密码和mysql 密码，请和下面的service配置保持一致
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
      # Token 过期时间
      - TOKEN_EXPIRETIME=36000000000
      # 缓存过期时间
      - SPRING_CACHE_REDIS_TIME-TO-LIVE=60s
      # 花里胡哨
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    ports:
      - 8080:8080

  # 数据库
  db:
    container_name: attendance_db
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=attendance
      - MYSQL_DATABASE=Attendance
    #    ports:
    #      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  # 数据库管理工具
  phpmyadmin:
    image: phpmyadmin
    container_name: attendance_phpmyadmin
    environment:
      - TZ=Asia/Shanghai
      - PMA_HOST=db
      # - PMA_ABSOLUTE_URI=http://127.0.0.1:8081/
    ports:
      # 数据库管理端口
      - 8081:80
    volumes:
      - padm_sess:/sessions
    depends_on:
      - db
  redis:
    container_name: attendance_redis
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - TZ=Asia/Shanghai

volumes:
  db:
    name: atds_db
  # 可以映射到主机的maven 缓存
  m2:
    name: m2
  gradle:
    name: gradle
  padm_sess:
    name: atds_padm_sess

